Assign user to mr and issues

diff --git a/create_mr b/create_mr
--- a/create_mr
+++ b/create_mr
@@ -1,9 +1,9 @@
 #! /bin/sh
-if ! ISSUE_LIST=$(lab --no-pager issue list); then
-        exit 1;
-fi
+USERNAME="ace966"
 
-ISSUE=$(echo "$ISSUE_LIST" | sed 's/#//g' | tr -cd '[:alnum:]- \n' | tr '[:upper:]' '[:lower:]' | sed 's/\ /-/g' | rofi -i -p Issue -markup-rows -dmenu)
+ISSUE_LIST=$(lab issue list) || exit 1
+
+ISSUE=$(echo "$ISSUE_LIST" | sed 's/#//g' | tr -cd '[:alnum:]- \n' | tr '[:upper:]' '[:lower:]' | sed 's/\ /-/g' | rofi -i -p ISSUE -markup-rows -dmenu)
 
 [ -n "$ISSUE" ] || (echo "No issue selected. Aborting..."; exit 0;)
 
@@ -13,5 +13,6 @@ MR_TITLE=$(echo "$ISSUE_LIST" | grep "$ISSUE_NR" | sed 's/\#[0-9]*\ //g')
 git checkout -b "$ISSUE"
 git push -u origin "$ISSUE"
 
-lab mr create --draft -s -m  "$MR_TITLE" -m "Closes #$ISSUE_NR"
+lab issue edit "$ISSUE_NR" -a "$USERNAME" || echo "Failed to set user"
+lab mr create -s -m  "Draft: $MR_TITLE" -m "Closes #$ISSUE_NR" -a "$USERNAME"
 
